### ISSUE TITLE
having issue installing.

### ISSUE THREAD

**Issue by tymiles003** [iuricmp/traccar-fleet#1]
You can however run a command with sudo using --allow-root option
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9:28.733s
[INFO] Finished at: Fri Dec 04 09:46:52 EST 2015
[INFO] Final Memory: 41M/511M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.trecloux:yeoman-maven-plugin:0.4:build (run-frontend-build) on project fleet: Error during : bower install --no-color: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
root@myvm-virtual-machine:/opt/traccar-fleet#

**Comment by iuricmp** [comment]
fixed
